
name: HAM — Blog
title: Haley Archer-McClellan
description: "A Blog About Nothing"
url: https://harchermcclellan.github.io/blog
baseurl: "/blog"
permalink: /posts/:title/
markdown: kramdown
repository: "harchermcclellan/harchermcclellan.github.io"

feed:
  categories:
    - ruby

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc